### ISSUE TITLE
Include "scoringRules" into the dependencies list

### ISSUE THREAD

**Issue by sergeikharchenko** [tchalauxclergue/fingR#2]
Update. Ahah, sorry, I'm not very attentive))
#> Le chargement a nécessité le package : scoringRules

Dear colleague!
I found out, that the code requests "scoringRules" here:
BMM.CRPS <- fingR::CRPS(obs = VM.contrib,                                             # Observed contributions
                        prev = read.csv(paste0(dir.mod.BMM, "BMM_prevision_VM.csv")), # Predicted prevision from BMM saved by `rum.BMM()`
                        source.groups = c("Forest", "Subsoil", "Undecontaminated"),   # Source class groups
                        mean.cal = TRUE,                                              # Calculate mean CRPS per source class group
                        save.dir = dir.mod.BMM,                                       # Optional: Directory path for saving the results
                        #note = "example"                                             # Optional: Additional note to append to the file name
                        )

But it hasn't been included in the dependencies list. Maybe it'll be useful. Great thanks for the package!

**Comment by tchalauxclergue** [comment]
Dear Sergei,
Thank you for spotting that! I fixed that in a new release (v. 2.1.1).
Best, Thomas

**Comment by tchalauxclergue** [comment]
Dear Sergei,
Thank you for spotting that! I fixed that in a new release (v. 2.1.1).
Best, Thomas
